cmake_minimum_required(VERSION 3.20)
project(p3d_consumer LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(p3d CONFIG REQUIRED)
add_executable(p3d-consumer consumer.cpp)
target_link_libraries(p3d-consumer PRIVATE p3d::reader)
if(WIN32)
 target_link_libraries(p3d-consumer PRIVATE shell32)
endif()
