#include <p3d/csg_mesh_tree.hpp>
#include <p3d/csg.hpp>
#include "geometry.hpp"

namespace p3d {
namespace {
using Mesh = std::shared_ptr<CsgTreeMesh>;
struct Runtime;
struct Object {
    Mesh mesh;
    std::shared_ptr<Runtime> nested;
    bool solid = false;
    std::shared_ptr<Json> cone;
    Object(Mesh value, bool is_solid = false) : mesh(std::move(value)), solid(is_solid) {}
    Object(std::shared_ptr<Runtime> value) : nested(std::move(value)) {}
};
struct Work {
    const CsgMeshTreeOptions &options;
    std::size_t operations = 0, cached_triangles = 0, transformed_vertices = 0;
    std::size_t cached_meshes = 0, nodes = 0, node_updates = 0, geometry_visits = 0;
    std::size_t solid_triangles = 0, solid_conversions = 0;
    std::string status = "not_evaluated";
    void limit(bool valid, const char *why) {
        if (!valid) {
            status = "work_limit";
            require(false, why);
        }
    }
};
struct Runtime {
    Json state;
    Work &work;
    const CsgMeshTreeOptions &options;
    std::vector<Object> geometry, caches;
    std::size_t &operations, &cached_triangles, &transformed_vertices;
    std::string &status;
    std::optional<std::size_t> current_node;

    Runtime(const Json &archive, Work &budget)
        : work(budget), options(work.options), operations(work.operations),
          cached_triangles(work.cached_triangles), transformed_vertices(work.transformed_vertices),
          status(work.status) {
        const auto count = archive.at("tree").at("nodes").size();
        work.limit(count <= options.max_nodes - work.nodes, "CSG aggregate node budget exceeded");
        work.nodes += count;
        // Nested payloads are owned by child runtimes, not duplicated in every ancestor.
        state = {{"tree", archive.at("tree")},
                 {"transforms", archive.at("transforms")},
                 {"geometries", Json::array()},
                 {"node_caches", Json::array()}};
        for (std::size_t i = 0; i < archive.at("geometries").size(); ++i)
            state["geometries"].push_back(nullptr);
    }

    void limit(bool valid, const char *why) {
        work.limit(valid, why);
    }
    Matrix4 matrix(std::size_t node) {
        const auto input = csg_node_geometry_input(state, node);
        require(input.at("status") == "source_selection_known", "CSG unresolved node input");
        const auto rows = input.at("node_transform").at("matrix_3x4_rows");
        auto out = identity();
        require(rows.is_array() && rows.size() == 3, "CSG transform row count");
        for (unsigned r = 0; r < 3; ++r) {
            require(rows.at(r).is_array() && rows.at(r).size() == 4, "CSG transform column count");
            for (unsigned c = 0; c < 4; ++c) {
                out[r][c] = rows.at(r).at(c).get<double>();
                require(std::isfinite(out[r][c]), "CSG nonfinite transform");
            }
        }
        return out;
    }
    std::vector<Object> select(std::size_t node) {
        // The native accessor resolves against the CURRENT cache pool, including
        // cache objects generated by earlier nodes in this very update.
        const auto input = csg_node_geometry_input(state, node);
        require(input.at("status") == "source_selection_known", "CSG unresolved source selection");
        std::vector<Object> out;
        for (const auto &ref : input.at("selected_sources")) {
            const auto i = ref.at("target_index").get<std::size_t>();
            out.push_back(ref.at("list") == "geometries" ? geometry.at(i) : caches.at(i));
        }
        return out;
    }
    void transform_object(const Object &object, const Matrix4 &m) {
        limit(work.geometry_visits < options.max_geometry_visits,
              "CSG geometry visit budget exceeded");
        ++work.geometry_visits;
        if (object.mesh) {
            if (object.cone) {
                auto placed = transform_bgfb_cone(*object.cone, m);
                if (placed.status != "transformed")
                    throw std::runtime_error(
                        placed.report.value("reason", std::string("CSG cone placement failed")));
                place({object.mesh}, placed.geometry_transform);
                *object.cone = std::move(placed.transformed);
            } else
                place({object.mesh}, m);
        } else {
            // Native GeCsgTree::transformInPlace visits the original pool and
            // CURRENT caches separately. Aliases may therefore be transformed twice.
            for (const auto &child : object.nested->geometry)
                transform_object(child, m);
            for (const auto &child : object.nested->caches)
                transform_object(child, m);
        }
    }
    std::vector<Mesh> convert(const std::vector<Object> &input, const Matrix4 &m) {
        std::vector<Mesh> out;
        for (const auto &object : input) {
            transform_object(object, m);
            std::vector<Mesh> values;
            if (object.solid) {
                limit(object.mesh->faces.size() <=
                          options.max_solid_triangles - work.solid_triangles,
                      "CSG solid conversion triangle budget exceeded");
                work.solid_triangles += object.mesh->faces.size();
                ++work.solid_conversions;
            }
            if (object.mesh)
                // A solid is tessellated into a fresh Polyface on EACH visit.
                // transform_object applies each supported solid's placement rule;
                // copying its derived triangles preserves distinct object identity.
                values.push_back(object.solid ? std::make_shared<CsgTreeMesh>(*object.mesh)
                                              : object.mesh);
            else {
                object.nested->run_update();
                values = object.nested->root_meshes();
            }
            limit(values.size() <= options.max_geometry_visits - out.size(),
                  "CSG expanded source mesh count limit");
            out.insert(out.end(), values.begin(), values.end());
        }
        return out;
    }
    void run_update() {
        const auto root = state.at("tree").at("root_index");
        if (root.is_null())
            return;
        caches.clear();
        state["node_caches"] = Json::array();
        update(root.get<std::size_t>());
    }
    std::vector<Mesh> root_meshes() {
        const auto root = state.at("tree").at("root_index");
        return root.is_null() ? std::vector<Mesh>{}
                              : convert(select(root.get<std::size_t>()), identity());
    }
    void place(const std::vector<Mesh> &input, const Matrix4 &m) {
        const double det = determinant(m);
        require(std::isfinite(det) && det != 0, "CSG singular or overflowing mesh transform");
        for (const auto &mesh : input) {
            limit(mesh->vertices.size() <= options.max_vertex_transforms - transformed_vertices,
                  "CSG vertex transformation budget exceeded");
            transformed_vertices += mesh->vertices.size();
            for (auto &p : mesh->vertices) {
                p = transform(m, p);
                for (double x : p)
                    require(std::isfinite(x), "CSG transformed position overflow");
            }
            for (std::size_t f = 0; f < mesh->faces.size(); ++f) {
                auto &source = mesh->face_sources[f];
                source.source_to_result = multiply(m, source.source_to_result);
                for (const auto &row : source.source_to_result)
                    for (double x : row)
                        require(std::isfinite(x), "CSG accumulated transform overflow");
                if (det < 0) {
                    std::swap(mesh->faces[f][1], mesh->faces[f][2]);
                    std::swap(source.corner_barycentric[1], source.corner_barycentric[2]);
                }
            }
        }
    }
    static std::vector<Geometry> operands(const std::vector<Mesh> &input) {
        std::vector<Geometry> out;
        for (const auto &mesh : input) {
            Geometry g;
            g.vertices = mesh->vertices;
            g.faces = mesh->faces;
            out.push_back(std::move(g));
        }
        return out;
    }
    std::vector<Mesh> calculate(const std::vector<Mesh> &left, const std::vector<Mesh> &right,
                                int operation, bool leaf) {
        auto limits = options.boolean;
        limits.max_boolean_operations -= operations;
        const auto a = operands(left), b = operands(right);
        auto result = leaf ? reduce_csg_mesh_list(a, operation, limits)
                           : evaluate_csg_mesh_lists(a, b, operation, limits);
        operations += result.diagnostics.value("boolean_operations", std::size_t(0));
        if (result.status != "evaluated") {
            status = result.status;
            require(false, result.diagnostics.dump());
        }
        std::vector<Mesh> out;
        for (auto &group : result.groups) {
            if (group.mesh.diagnostics.value("passthrough", false)) {
                // A new IGeometry wrapper can still point to the SAME Polyface.
                // Later placements must be observed through both references.
                out.push_back(group.left_indices.empty() ? right.at(group.right_indices.at(0))
                                                         : left.at(group.left_indices.at(0)));
                continue;
            }
            auto mesh = std::make_shared<CsgTreeMesh>();
            mesh->vertices = std::move(group.mesh.vertices);
            mesh->faces = std::move(group.mesh.faces);
            for (const auto &face : group.mesh.face_sources) {
                const auto &input = face.operand ? right : left;
                const auto &parent = input.at(face.mesh_index)->face_sources.at(face.face_index);
                CsgTreeTriangleSource source = parent;
                source.backside = source.backside != face.backside;
                source.corner_barycentric = {};
                for (unsigned k = 0; k < 3; ++k)
                    for (unsigned j = 0; j < 3; ++j)
                        for (unsigned v = 0; v < 3; ++v)
                            source.corner_barycentric[k][v] +=
                                face.corner_barycentric[k][j] * parent.corner_barycentric[j][v];
                mesh->face_sources.push_back(source);
            }
            out.push_back(std::move(mesh));
        }
        return out;
    }
    void update(std::size_t root) {
        auto &nodes = state.at("tree").at("nodes");
        limit(nodes.size() <= options.max_nodes, "CSG node budget exceeded");
        std::vector<unsigned char> visited(nodes.size());
        std::vector<std::pair<std::size_t, bool>> pending{{root, false}};
        while (!pending.empty()) {
            const auto [id, finish] = pending.back();
            pending.pop_back();
            current_node = id;
            require(id < nodes.size(), "CSG child index out of range");
            auto &node = nodes[id];
            require(node.value("status", "") == "decoded" ||
                        node.value("status", "") == "decoded_with_trailing_bytes",
                    "CSG node layout unavailable");
            const bool leaf = node.at("left_index").is_null() && node.at("right_index").is_null();
            const auto op = node.at("operation").get<std::int32_t>();
            if (!finish) {
                limit(work.node_updates < options.max_node_updates,
                      "CSG node update budget exceeded");
                ++work.node_updates;
                require(visited[id] == 0,
                        "CSG cyclic or shared node graph is not a persisted tree");
                visited[id] = 1;
                pending.push_back({id, true});
                for (const char *side : {"right_index", "left_index"})
                    if (!node.at(side).is_null())
                        pending.push_back({node.at(side).get<std::size_t>(), false});
                continue;
            }
            visited[id] = 2;
            if (leaf && std::uint32_t(op) > 1)
                continue;
            if (op == 3) {
                node["geometry_indices"] = Json::array();
                node["cache_indices"] = Json::array();
                for (const char *side : {"left_index", "right_index"}) {
                    if (node.at(side).is_null())
                        continue;
                    const auto &child = nodes.at(node.at(side).get<std::size_t>());
                    const char *list =
                        child.at("geometry_indices").empty() ? "cache_indices" : "geometry_indices";
                    for (const auto &index : child.at(list))
                        node[list].push_back(index);
                }
                continue;
            }
            if (std::uint32_t(op) > 2)
                continue;
            std::vector<Mesh> a, b;
            if (leaf) {
                node["is_old_value"] = 1;
                const auto input = select(id);
                node["is_old_value"] = 0;
                a = convert(input, matrix(id));
            } else {
                const auto l = node.at("left_index"), r = node.at("right_index");
                std::vector<Object> left, right;
                if (!l.is_null())
                    left = select(l.get<std::size_t>());
                if (!r.is_null())
                    right = select(r.get<std::size_t>());
                // Selection of both sides precedes conversion. Because lists
                // retain object references, right placement can change objects
                // already selected and transformed on the left.
                if (!l.is_null())
                    a = convert(left, matrix(l.get<std::size_t>()));
                if (!r.is_null())
                    b = convert(right, matrix(r.get<std::size_t>()));
            }
            auto values = calculate(a, b, op, leaf);
            node["cache_indices"] = Json::array();
            for (auto &mesh : values) {
                limit(mesh->faces.size() <= options.max_cached_triangles - cached_triangles,
                      "CSG generated cache triangle budget exceeded");
                limit(caches.size() < std::size_t(INT32_MAX), "CSG cache index overflow");
                limit(work.cached_meshes < options.max_cached_meshes,
                      "CSG generated cache count limit");
                ++work.cached_meshes;
                cached_triangles += mesh->faces.size();
                node["cache_indices"].push_back(caches.size());
                caches.push_back(std::move(mesh));
                state["node_caches"].push_back(nullptr);
            }
        }
    }
};

Mesh source_mesh(const Geometry &g, std::size_t index,
                 CsgSourceKind kind = CsgSourceKind::polyface) {
    require(g.lines.empty() && g.texts.empty() && g.unknown.empty(), "CSG unresolved source mesh");
    auto mesh = std::make_shared<CsgTreeMesh>();
    mesh->vertices = g.vertices;
    mesh->faces = g.faces;
    for (const auto &p : g.vertices)
        for (double v : p)
            require(std::isfinite(v), "CSG nonfinite source position");
    for (std::size_t f = 0; f < g.faces.size(); ++f) {
        CsgTreeTriangleSource source;
        source.geometry_index = index;
        source.source_kind = kind;
        source.face_index = f;
        source.source_to_result = identity();
        for (unsigned k = 0; k < 3; ++k) {
            require(g.faces[f][k] < g.vertices.size(), "CSG source face index out of range");
            source.corner_barycentric[k][k] = 1;
        }
        mesh->face_sources.push_back(source);
    }
    return mesh;
}
void evaluate(Runtime &runtime, const std::vector<const Geometry *> &source_meshes,
              CsgMeshTreeResult &result, const std::vector<const Geometry *> &solid_meshes = {}) {
    runtime.run_update();
    const auto selected = runtime.root_meshes();
    runtime.limit(selected.size() <= runtime.options.boolean.max_output_groups,
                  "CSG root mesh count limit");
    std::size_t triangles = 0;
    for (const auto &mesh : selected) {
        runtime.limit(mesh->faces.size() <=
                          runtime.options.boolean.mesh.max_output_triangles - triangles,
                      "CSG root triangle count limit");
        triangles += mesh->faces.size();
        auto output = *mesh;
        for (std::size_t f = 0; f < output.faces.size(); ++f) {
            auto &source = output.face_sources[f];
            const auto &pool =
                source.source_kind == CsgSourceKind::solid ? solid_meshes : source_meshes;
            const auto &g = *pool.at(source.geometry_index);
            for (unsigned k = 0; k < 3; ++k) {
                Point3 point{};
                for (unsigned j = 0; j < 3; ++j)
                    for (unsigned axis = 0; axis < 3; ++axis)
                        point[axis] += source.corner_barycentric[k][j] *
                                       g.vertices.at(g.faces.at(source.face_index)[j])[axis];
                point = transform(source.source_to_result, point);
                const auto &actual = output.vertices.at(output.faces[f][k]);
                source.corner_projection_distance[k] =
                    std::hypot(point[0] - actual[0], point[1] - actual[1], point[2] - actual[2]);
                require(std::isfinite(source.corner_projection_distance[k]),
                        "CSG source projection overflow");
            }
        }
        result.meshes.push_back(std::move(output));
    }
    for (const auto &node : runtime.state.at("tree").at("nodes"))
        result.updated_nodes.push_back({{"geometry_indices", node.at("geometry_indices")},
                                        {"cache_indices", node.at("cache_indices")},
                                        {"is_old_value", node.at("is_old_value")}});
    result.status = "evaluated";
}
void diagnostics(CsgMeshTreeResult &result, const Work &work) {
    result.diagnostics["scope"] = "derived_polyface_tree_update";
    result.diagnostics["native_kernel_equivalence"] = "not_established";
    result.diagnostics["native_cache_cardinality"] = "not_established";
    result.diagnostics["boolean_operations"] = work.operations;
    result.diagnostics["generated_cache_count"] = work.cached_meshes;
    result.diagnostics["vertex_transforms"] = work.transformed_vertices;
    result.diagnostics["node_updates"] = work.node_updates;
    result.diagnostics["geometry_visits"] = work.geometry_visits;
    result.diagnostics["solid_mesh_conversions"] = work.solid_conversions;
    result.diagnostics["solid_triangles"] = work.solid_triangles;
}
void failure(CsgMeshTreeResult &result, const Work &work, const std::exception &error) {
    result.status = work.status;
    result.meshes.clear();
    result.updated_nodes.clear();
    result.diagnostics["reason"] = error.what();
}
void validate_options(const CsgMeshTreeOptions &options) {
    require(std::isfinite(options.boolean.mesh.tolerance) && options.boolean.mesh.tolerance >= 0,
            "CSG invalid mesh tolerance");
    require(options.max_archive_depth <= 128, "CSG archive depth hard limit is 128");
}
std::shared_ptr<Runtime> load_archive(const Json &archive, Work &work,
                                      CsgPolyfaceArchiveResult &out, PolyfaceMeshOptions &budget,
                                      std::size_t depth, const Json &path) {
    work.limit(depth <= work.options.max_archive_depth, "CSG archive depth budget exceeded");
    auto runtime = std::make_shared<Runtime>(archive, work);
    // Root update discards its saved caches before any transform. A nested
    // object, however, transforms its saved caches BEFORE running that update.
    for (const char *list : {"geometries", "node_caches"}) {
        if (depth == 0 && std::string(list) == "node_caches")
            continue;
        auto &pool = std::string(list) == "geometries" ? runtime->geometry : runtime->caches;
        const auto &entries = archive.at(list);
        for (std::size_t i = 0; i < entries.size(); ++i) {
            work.limit(work.geometry_visits < work.options.max_geometry_visits,
                       "CSG geometry loading budget exceeded");
            ++work.geometry_visits;
            auto child_path = path;
            child_path.push_back({{"list", list}, {"index", i}});
            out.result.diagnostics["source_path"] = child_path;
            const auto &entry = entries.at(i);
            require(entry.at("status") == "decoded", "CSG source entry is not decoded");
            if (entry.at("encoding") == "csg_archive") {
                pool.emplace_back(
                    load_archive(entry.at("geometry"), work, out, budget, depth + 1, child_path));
            } else {
                require(entry.at("encoding") == "bgfb", "CSG unsupported source encoding");
                const auto &table = entry.at("geometry").at("geometry");
                const bool solid = table.at("_type") != "Polyface";
                const auto index = solid ? out.solid_sources.size() : out.sources.size();
                if (solid) {
                    out.solid_sources.push_back(
                        mesh_bgfb_solid(table, budget, work.options.solid_circle_segments));
                    out.solid_source_paths.push_back(child_path);
                } else {
                    out.sources.push_back(mesh_bgfb_polyface(table, budget));
                    out.source_paths.push_back(child_path);
                }
                const auto &source = solid ? out.solid_sources.back().derived : out.sources.back();
                if (source.status != "meshed")
                    throw std::runtime_error(source.report.value(
                        "reason", std::string("CSG source triangulation failed")));
                const auto &g = source.geometry;
                budget.max_points -= g.vertices.size();
                budget.max_triangles -= g.faces.size();
                budget.max_corners -= source.report.at("source_corner_count").get<std::size_t>();
                budget.max_polygon_edge_tests -=
                    source.report.at("polygon_edge_tests").get<std::size_t>();
                pool.emplace_back(
                    source_mesh(g, index, solid ? CsgSourceKind::solid : CsgSourceKind::polyface),
                    solid);
                if (solid && table.at("_type") == "DgnCone")
                    pool.back().cone = std::make_shared<Json>(table);
            }
            if (std::string(list) == "node_caches")
                runtime->state["node_caches"].push_back(nullptr);
        }
    }
    return runtime;
}
} // namespace
CsgMeshTreeResult evaluate_csg_polyface_tree(const Json &archive,
                                             const std::vector<Geometry> &source_meshes,
                                             const CsgMeshTreeOptions &options) {
    CsgMeshTreeResult result;
    Work work{options};
    std::unique_ptr<Runtime> runtime;
    try {
        validate_options(options);
        runtime = std::make_unique<Runtime>(archive, work);
        require(archive.at("geometries").size() == source_meshes.size(),
                "CSG source mesh count mismatch");
        std::vector<const Geometry *> sources;
        for (std::size_t i = 0; i < source_meshes.size(); ++i) {
            const auto &entry = archive.at("geometries").at(i);
            require(entry.at("status") == "decoded" && entry.at("encoding") == "bgfb" &&
                        entry.at("geometry").at("geometry").at("_type") == "Polyface",
                    "CSG tree mesh backend requires original Polyface sources");
            runtime->geometry.emplace_back(source_mesh(source_meshes[i], i));
            sources.push_back(&source_meshes[i]);
        }
        evaluate(*runtime, sources, result);
    } catch (const std::exception &e) {
        failure(result, work, e);
        if (runtime && runtime->current_node)
            result.diagnostics["node_index"] = *runtime->current_node;
    }
    diagnostics(result, work);
    return result;
}
CsgPolyfaceArchiveResult evaluate_csg_polyface_archive(const Json &archive,
                                                       const CsgMeshTreeOptions &tree_options,
                                                       const PolyfaceMeshOptions &mesh_options) {
    CsgPolyfaceArchiveResult out;
    Work work{tree_options};
    auto budget = mesh_options;
    try {
        validate_options(tree_options);
        auto runtime = load_archive(archive, work, out, budget, 0, Json::array());
        out.result.diagnostics.erase("source_path");
        std::vector<const Geometry *> sources;
        for (const auto &source : out.sources)
            sources.push_back(&source.geometry);
        std::vector<const Geometry *> solid_sources;
        for (const auto &source : out.solid_sources)
            solid_sources.push_back(&source.derived.geometry);
        evaluate(*runtime, sources, out.result, solid_sources);
    } catch (const std::exception &e) {
        failure(out.result, work, e);
    }
    diagnostics(out.result, work);
    return out;
}
} // namespace p3d
