#include <p3d/csg_mesh_tree.hpp>
#include <p3d/csg.hpp>
#include "geometry.hpp"

namespace p3d {
namespace {
using Mesh = std::shared_ptr<CsgTreeMesh>;
struct Runtime {
    Json state;
    const CsgMeshTreeOptions &options;
    std::vector<Mesh> geometry, caches;
    std::size_t operations = 0, cached_triangles = 0, transformed_vertices = 0;
    std::string status = "not_evaluated";
    std::optional<std::size_t> current_node;

    Runtime(const Json &archive, const CsgMeshTreeOptions &settings)
        : state(archive), options(settings) {}

    void limit(bool valid, const char *why) {
        if (!valid) {
            status = "work_limit";
            require(false, why);
        }
    }
    Matrix4 matrix(std::size_t node) {
        const auto input = csg_node_geometry_input(state, node);
        require(input.at("status") == "source_selection_known", "CSG unresolved node input");
        const auto rows = input.at("node_transform").at("matrix_3x4_rows");
        auto out = identity();
        require(rows.is_array() && rows.size() == 3, "CSG transform row count");
        for (unsigned r = 0; r < 3; ++r) {
            require(rows.at(r).is_array() && rows.at(r).size() == 4, "CSG transform column count");
            for (unsigned c = 0; c < 4; ++c) {
                out[r][c] = rows.at(r).at(c).get<double>();
                require(std::isfinite(out[r][c]), "CSG nonfinite transform");
            }
        }
        return out;
    }
    std::vector<Mesh> select(std::size_t node) {
        // The native accessor resolves against the CURRENT cache pool, including
        // cache objects generated by earlier nodes in this very update.
        const auto input = csg_node_geometry_input(state, node);
        require(input.at("status") == "source_selection_known", "CSG unresolved source selection");
        std::vector<Mesh> out;
        for (const auto &ref : input.at("selected_sources")) {
            const auto i = ref.at("target_index").get<std::size_t>();
            out.push_back(ref.at("list") == "geometries" ? geometry.at(i) : caches.at(i));
        }
        return out;
    }
    void place(const std::vector<Mesh> &input, const Matrix4 &m) {
        const double det = determinant(m);
        require(std::isfinite(det) && det != 0, "CSG singular or overflowing mesh transform");
        for (const auto &mesh : input) {
            limit(mesh->vertices.size() <= options.max_vertex_transforms - transformed_vertices,
                  "CSG vertex transformation budget exceeded");
            transformed_vertices += mesh->vertices.size();
            for (auto &p : mesh->vertices) {
                p = transform(m, p);
                for (double x : p)
                    require(std::isfinite(x), "CSG transformed position overflow");
            }
            for (std::size_t f = 0; f < mesh->faces.size(); ++f) {
                auto &source = mesh->face_sources[f];
                source.source_to_result = multiply(m, source.source_to_result);
                for (const auto &row : source.source_to_result)
                    for (double x : row)
                        require(std::isfinite(x), "CSG accumulated transform overflow");
                if (det < 0) {
                    std::swap(mesh->faces[f][1], mesh->faces[f][2]);
                    std::swap(source.corner_barycentric[1], source.corner_barycentric[2]);
                }
            }
        }
    }
    static std::vector<Geometry> operands(const std::vector<Mesh> &input) {
        std::vector<Geometry> out;
        for (const auto &mesh : input) {
            Geometry g;
            g.vertices = mesh->vertices;
            g.faces = mesh->faces;
            out.push_back(std::move(g));
        }
        return out;
    }
    std::vector<Mesh> calculate(const std::vector<Mesh> &left, const std::vector<Mesh> &right,
                                int operation, bool leaf) {
        auto limits = options.boolean;
        limits.max_boolean_operations -= operations;
        const auto a = operands(left), b = operands(right);
        auto result = leaf ? reduce_csg_mesh_list(a, operation, limits)
                           : evaluate_csg_mesh_lists(a, b, operation, limits);
        operations += result.diagnostics.value("boolean_operations", std::size_t(0));
        if (result.status != "evaluated") {
            status = result.status;
            require(false, result.diagnostics.dump());
        }
        std::vector<Mesh> out;
        for (auto &group : result.groups) {
            if (group.mesh.diagnostics.value("passthrough", false)) {
                // A new IGeometry wrapper can still point to the SAME Polyface.
                // Later placements must be observed through both references.
                out.push_back(group.left_indices.empty() ? right.at(group.right_indices.at(0))
                                                         : left.at(group.left_indices.at(0)));
                continue;
            }
            auto mesh = std::make_shared<CsgTreeMesh>();
            mesh->vertices = std::move(group.mesh.vertices);
            mesh->faces = std::move(group.mesh.faces);
            for (const auto &face : group.mesh.face_sources) {
                const auto &input = face.operand ? right : left;
                const auto &parent = input.at(face.mesh_index)->face_sources.at(face.face_index);
                CsgTreeTriangleSource source = parent;
                source.backside = source.backside != face.backside;
                source.corner_barycentric = {};
                for (unsigned k = 0; k < 3; ++k)
                    for (unsigned j = 0; j < 3; ++j)
                        for (unsigned v = 0; v < 3; ++v)
                            source.corner_barycentric[k][v] +=
                                face.corner_barycentric[k][j] * parent.corner_barycentric[j][v];
                mesh->face_sources.push_back(source);
            }
            out.push_back(std::move(mesh));
        }
        return out;
    }
    void update(std::size_t root) {
        auto &nodes = state.at("tree").at("nodes");
        limit(nodes.size() <= options.max_nodes, "CSG node budget exceeded");
        std::vector<unsigned char> visited(nodes.size());
        std::vector<std::pair<std::size_t, bool>> pending{{root, false}};
        while (!pending.empty()) {
            const auto [id, finish] = pending.back();
            pending.pop_back();
            current_node = id;
            require(id < nodes.size(), "CSG child index out of range");
            auto &node = nodes[id];
            require(node.value("status", "") == "decoded" ||
                        node.value("status", "") == "decoded_with_trailing_bytes",
                    "CSG node layout unavailable");
            const bool leaf = node.at("left_index").is_null() && node.at("right_index").is_null();
            const auto op = node.at("operation").get<std::int32_t>();
            if (!finish) {
                require(visited[id] == 0,
                        "CSG cyclic or shared node graph is not a persisted tree");
                visited[id] = 1;
                pending.push_back({id, true});
                for (const char *side : {"right_index", "left_index"})
                    if (!node.at(side).is_null())
                        pending.push_back({node.at(side).get<std::size_t>(), false});
                continue;
            }
            visited[id] = 2;
            if (leaf && std::uint32_t(op) > 1)
                continue;
            if (op == 3) {
                node["geometry_indices"] = Json::array();
                node["cache_indices"] = Json::array();
                for (const char *side : {"left_index", "right_index"}) {
                    if (node.at(side).is_null())
                        continue;
                    const auto &child = nodes.at(node.at(side).get<std::size_t>());
                    const char *list =
                        child.at("geometry_indices").empty() ? "cache_indices" : "geometry_indices";
                    for (const auto &index : child.at(list))
                        node[list].push_back(index);
                }
                continue;
            }
            if (std::uint32_t(op) > 2)
                continue;
            std::vector<Mesh> a, b;
            if (leaf) {
                node["is_old_value"] = 1;
                a = select(id);
                node["is_old_value"] = 0;
                place(a, matrix(id));
            } else {
                const auto l = node.at("left_index"), r = node.at("right_index");
                if (!l.is_null())
                    a = select(l.get<std::size_t>());
                if (!r.is_null())
                    b = select(r.get<std::size_t>());
                // Selection of both sides precedes conversion. Because lists
                // retain object references, right placement can change objects
                // already selected and transformed on the left.
                if (!l.is_null())
                    place(a, matrix(l.get<std::size_t>()));
                if (!r.is_null())
                    place(b, matrix(r.get<std::size_t>()));
            }
            auto values = calculate(a, b, op, leaf);
            node["cache_indices"] = Json::array();
            for (auto &mesh : values) {
                limit(mesh->faces.size() <= options.max_cached_triangles - cached_triangles,
                      "CSG generated cache triangle budget exceeded");
                limit(caches.size() < std::size_t(INT32_MAX), "CSG cache index overflow");
                limit(caches.size() < options.max_cached_meshes, "CSG generated cache count limit");
                cached_triangles += mesh->faces.size();
                node["cache_indices"].push_back(caches.size());
                caches.push_back(std::move(mesh));
                state["node_caches"].push_back(nullptr);
            }
        }
    }
};
} // namespace
CsgMeshTreeResult evaluate_csg_polyface_tree(const Json &archive,
                                             const std::vector<Geometry> &source_meshes,
                                             const CsgMeshTreeOptions &options) {
    CsgMeshTreeResult result;
    result.diagnostics = {{"scope", "derived_polyface_tree_update"},
                          {"native_kernel_equivalence", "not_established"},
                          {"native_cache_cardinality", "not_established"}};
    Runtime runtime{archive, options};
    try {
        require(std::isfinite(options.boolean.mesh.tolerance) &&
                    options.boolean.mesh.tolerance >= 0,
                "CSG invalid mesh tolerance");
        require(archive.at("geometries").size() == source_meshes.size(),
                "CSG source mesh count mismatch");
        for (std::size_t i = 0; i < source_meshes.size(); ++i) {
            const auto &entry = archive.at("geometries").at(i);
            require(entry.at("status") == "decoded" && entry.at("encoding") == "bgfb" &&
                        entry.at("geometry").at("geometry").at("_type") == "Polyface",
                    "CSG tree mesh backend requires original Polyface sources");
            const auto &g = source_meshes[i];
            require(g.lines.empty() && g.texts.empty() && g.unknown.empty(),
                    "CSG unresolved source mesh");
            auto mesh = std::make_shared<CsgTreeMesh>();
            mesh->vertices = g.vertices;
            mesh->faces = g.faces;
            for (const auto &p : g.vertices)
                for (double v : p)
                    require(std::isfinite(v), "CSG nonfinite source position");
            for (std::size_t f = 0; f < g.faces.size(); ++f) {
                CsgTreeTriangleSource source;
                source.geometry_index = i;
                source.face_index = f;
                source.source_to_result = identity();
                for (unsigned k = 0; k < 3; ++k) {
                    require(g.faces[f][k] < g.vertices.size(),
                            "CSG source face index out of range");
                    source.corner_barycentric[k][k] = 1;
                }
                mesh->face_sources.push_back(source);
            }
            runtime.geometry.push_back(std::move(mesh));
        }
        const auto root = archive.at("tree").at("root_index");
        if (!root.is_null()) {
            runtime.state["node_caches"] = Json::array();
            runtime.update(root.get<std::size_t>());
            const auto selected = runtime.select(root.get<std::size_t>());
            std::size_t triangles = 0;
            runtime.limit(selected.size() <= options.boolean.max_output_groups,
                          "CSG root mesh count limit");
            for (const auto &mesh : selected) {
                runtime.limit(mesh->faces.size() <=
                                  options.boolean.mesh.max_output_triangles - triangles,
                              "CSG root triangle count limit");
                triangles += mesh->faces.size();
                auto output = *mesh;
                for (std::size_t f = 0; f < output.faces.size(); ++f) {
                    auto &source = output.face_sources[f];
                    const auto &g = source_meshes.at(source.geometry_index);
                    for (unsigned k = 0; k < 3; ++k) {
                        Point3 point{};
                        for (unsigned j = 0; j < 3; ++j)
                            for (unsigned axis = 0; axis < 3; ++axis)
                                point[axis] +=
                                    source.corner_barycentric[k][j] *
                                    g.vertices.at(g.faces.at(source.face_index)[j])[axis];
                        point = transform(source.source_to_result, point);
                        const auto &actual = output.vertices.at(output.faces[f][k]);
                        source.corner_projection_distance[k] = std::hypot(
                            point[0] - actual[0], point[1] - actual[1], point[2] - actual[2]);
                        require(std::isfinite(source.corner_projection_distance[k]),
                                "CSG source projection overflow");
                    }
                }
                result.meshes.push_back(std::move(output));
            }
        }
        for (const auto &node : runtime.state.at("tree").at("nodes"))
            result.updated_nodes.push_back({{"geometry_indices", node.at("geometry_indices")},
                                            {"cache_indices", node.at("cache_indices")},
                                            {"is_old_value", node.at("is_old_value")}});
        result.status = "evaluated";
    } catch (const std::exception &e) {
        result.status = runtime.status;
        result.meshes.clear();
        result.updated_nodes.clear();
        result.diagnostics["reason"] = e.what();
        if (runtime.current_node)
            result.diagnostics["node_index"] = *runtime.current_node;
    }
    result.diagnostics["boolean_operations"] = runtime.operations;
    result.diagnostics["generated_cache_count"] = runtime.caches.size();
    result.diagnostics["vertex_transforms"] = runtime.transformed_vertices;
    return result;
}
CsgPolyfaceArchiveResult evaluate_csg_polyface_archive(const Json &archive,
                                                       const CsgMeshTreeOptions &tree_options,
                                                       const PolyfaceMeshOptions &mesh_options) {
    CsgPolyfaceArchiveResult out;
    std::vector<Geometry> meshes;
    auto budget = mesh_options;
    try {
        for (const auto &entry : archive.at("geometries")) {
            out.result.diagnostics["source_geometry_index"] = out.sources.size();
            require(entry.at("status") == "decoded" && entry.at("encoding") == "bgfb",
                    "CSG source requires a decoded BGFB Polyface");
            auto source = mesh_bgfb_polyface(entry.at("geometry").at("geometry"), budget);
            const bool meshed = source.status == "meshed";
            out.sources.push_back(std::move(source));
            require(meshed, out.sources.back().report.dump());
            const auto &g = out.sources.back().geometry;
            budget.max_points -= g.vertices.size();
            budget.max_triangles -= g.faces.size();
            budget.max_corners -=
                out.sources.back().report.at("source_corner_count").get<std::size_t>();
            budget.max_polygon_edge_tests -=
                out.sources.back().report.at("polygon_edge_tests").get<std::size_t>();
            meshes.push_back(g);
        }
        out.result = evaluate_csg_polyface_tree(archive, meshes, tree_options);
    } catch (const std::exception &e) {
        out.result.status = "not_evaluated";
        out.result.diagnostics["reason"] = e.what();
    }
    return out;
}
} // namespace p3d
